dist: xenial
language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - JEDI_TEST_ENVIRONMENT=27
  - JEDI_TEST_ENVIRONMENT=34
  - JEDI_TEST_ENVIRONMENT=35
  - JEDI_TEST_ENVIRONMENT=37

matrix:
  allow_failures:
    - python: pypy
    - env: TOXENV=sith
  include:
    - python: 3.6
      env:
        - TOXENV=cov
        - JEDI_TEST_ENVIRONMENT=36
    - python: 3.6
      env: TOXENV=sith
    # For now ignore pypy, there are so many issues that we don't really need
    # to run it.
    #- python: pypy
install:
    - pip install --quiet tox-travis
script:
    - tox
after_script:
    - |
      if [ $TOXENV == "cov" ]; then
        pip install --quiet codecov coveralls
        coverage xml
        coverage report -m
        coveralls
        bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X search -X fix -X xcode -f coverage.xml
      fi
